### ISSUE TITLE
Allow multiple selectors

### ISSUE THREAD

**Issue by beothorn** [beothorn/webGrude#11]
Allow multiple selectors. Ex:
@Seletor("h1 span", "h2 span")

**Comment by eallais** [comment]
Using repeatable annotation is a better aproach if this project only target jdk8

I already implemented this feature like this :
@Selector("h1 span")
@Selector("h2 span")

Are you interested?

Or using nested annotation for non jdk8
@Selectors(
 @Selector("h1 span"),
 @Selector("h2 span")
)

**Comment by beothorn** [comment]
Yes. If you open a PR I'll accept it, thanks.

**Comment by beothorn** [comment]
Thanks eallais, I've merged your changes and released a new version 2.1.1
